config/routes.rb
Todo::Application.routes.draw do

  namespace :api do
    resources :users, only: [:index, :create] do
      resources :lists, only: [:index, :create]
    end
  end

  resources :users do 
    resources :lists, except: [:index]
  end

  resources :lists, only: [] do
    resources :items, only: [:create, :new]
  end

  resources :items, only: [:destroy]

  root to: 'users#new'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  delegate :user, to: :list

  scope :completed, -> { where(completed: false) }

  def mark_complete
    update_attribute(:completed, true)
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items

  validates :name,  uniqueness: true

  scope :public, -> { where "permissions != 'private'" }

  def self.permission_options
    %w(private viewable open)
  end

  def add(item_description)
    if items.create(description: item_description)
      true
    else
      false
    end
  end

  def remove(item_description)
    if item = items.find_by(description: item_description)
      item.mark_complete
    else
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_many :items, through: :lists

  validates_presence_of :password, :username

  def authenticate?(pass)
    password == pass
  end

  def can?(action, list)
    case list.permissions
    when 'private'  then owns?(list)
    when 'visible'  then action == :view
    when 'open' then true
    else false
    end
  end

  private

  def owns?(list)
    list.user_id == id
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController
 
  def update
   list = List.find(params[:id])
   if list.update(list_params)
     render json: list
   else
     render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
   end
 end

  def index
    user = find_user
    return user_not_found_error unless user

    if params[:password] && user.authenticate?(params[:password])
      render json: user.lists
    else
      render json: user.lists.public
    end
  end

  def create
    user = find_user
    return user_not_found_error unless user
    return permission_denied_error if !user.authenticate?(params[:password])

    list = user.lists.build new_list_params
    if list.save
      render json: list, root: false, status: :created #201
    else
      error :unprocessable_entity, list.errors.full_messages #422
    end
  end

  private

  def new_list_params
    params.permit(:user_id, :name, :permissions)
  end

  def find_user
    User.where(id: params[:user_id]).first
  end


end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
 
  before_action :authenticated?
 
   def index
   end

 end
  def destroy
     begin
       user = User.find(params[:id])
       user.destroy
# #1
       render json: {}, status: :no_content
     rescue ActiveRecord::RecordNotFound
       render :json => {}, :status => :not_found
     end
   end

  def index
    return permission_denied_error unless authenticated?
    users = User.all
    render json: users, each_serializer: UsersSerializer
  end

  def create
    return permission_denied_error unless authenticated?
    user = User.new(new_user_params)
    if user.save
      render json: user, root: false, status: :created # 201
    else
      error :unprocessable_entity, user.errors.full_messages #422
    end
  end

  private

  def new_user_params
    params.permit(:username, :password)
  end

  def authenticated?
    authenticate_with_http_basic {|u, p| User.where( username: u, password: p).present? }
  end
def update
   list = List.find(params[:id])
   if list.update(list_params)
     render json: list
   else
     render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
   end
 end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
    private
    def authenticated?
 
     authenticate_or_request_with_http_basic {|username, password| User.where( username: username, password: password).present? }
   end
  respond_to :json

  private

  def permission_denied_error
    error(403, 'Permission Denied')
  end

  def user_not_found_error
    error(404, 'User not found')
  end

  def error(status, message = 'Something went wrong')
    response = {
      response_type: 'ERROR',
      message: message
    }
    render json: response.to_json, status: status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :update, :destroy]
  before_action :set_list

  def create
    
    if @list.add(item_params[:description])
      redirect_to user_list_path(@list.user, @list), notice: 'Item was successfully created.'
    else
      render action: 'new'
    end
  end

  def new
    @item = Item.new
  end

  def destroy
    @item.mark_complete
    redirect_to user_list_path(@list.user, @list)
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_list
    @list = @item ? @item.list : List.find(params[:list_id])
  end

  def item_params
    params.require(:item).permit(:description, :list_id, :completed)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_user
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def show
    @items = @list.items.completed
  end

  def new
    @list = List.new
  end

  def edit
  end

  def index
    @lists = @user.lists
  end

  def create
    @list = List.new(list_params)
    @list.user_id = @user.id

    if @list.save
      redirect_to user_list_path(@user, @list), notice: 'List was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @list.update(list_params)
      redirect_to user_list_path(@user, @list), notice: 'List was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @list.destroy
    redirect_to @user
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :user_id, :permissions)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @lists = @user.lists
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/new.html.haml
%h1= @list.name

= form_for [@list, @item] do |f|
  
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container{style: "margin-top: 200px"}
      = yield

app/views/lists/_form.html.haml
= form_for [@user, @list] do |f|
  - if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :permissions
    = f.select :permissions, options_for_select(List.permission_options)
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', user_list_path(@user, @list), class: 'btn'
\|
= link_to 'Back', @user, class: 'btn'

app/views/lists/index.html.haml
%h1= "#{@user.username}'s lists"

%table.table
  %tr
    %th Name
    %th User
    %th Permissions
    %th
    %th
    %th

  - @lists.each do |list|
    %tr
      %td= list.name
      %td= list.user_id
      %td= list.permissions
      %td= link_to 'Show', list, class: 'btn' 
      %td= link_to 'Edit', edit_list_path(list), class: 'btn' 
      %td= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn'

%br

= link_to 'New List', new_list_path, class: 'btn'

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', @user, class: 'btn'

app/views/lists/show.html.haml
%p#notice= notice

%h1 User Info
%p
  %b Name:
  = @list.name
%p
  %b User:
  = @user.username
%p
  %b Permissions:
  = @list.permissions

%h1 Items
%table.table
  %tr
    %th Description
    %th Mark Complete
  - @items.each do |item|
    %tr
      %td= item.description
      %td= link_to 'Mark Complete', item, method: :delete, class: 'btn'
%br
= link_to 'Add new item', new_list_item_path(@list), class: 'btn'
%br
%br
= link_to 'Edit', edit_user_list_path(@user, @list), class: 'btn'
\|
= link_to 'Back', @user, class: 'btn'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user, class: 'btn'
\|
= link_to 'Back', users_path, class: 'btn'

app/views/users/index.html.haml
%h1 Listing users

%table.table
  %tr
    %th Username
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= link_to 'Show', user, class: 'btn'
      %td= link_to 'Edit', edit_user_path(user), class: 'btn'
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn'

%br

= link_to 'New User', new_user_path, class: 'btn'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path, class: 'btn'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username

%h1 Lists
%table.table
  %tr
    %th List Name

  - @lists.each do |list|
    %tr
      %td= link_to list.name, user_list_path(@user, list), class: 'btn'

= link_to 'Add New List', new_user_list_path(@user), class: 'btn'

%br
%br

= link_to 'Edit', edit_user_path(@user), class: 'btn'
\|
= link_to 'Back', users_path, class: 'btn'